// monnify auth header
export const authString: string = Buffer.from(
  `${process.env.MONNIFY_API_KEY}:${process.env.MONNIFY_SECRET_KEY}`
).toString("base64");


export const Config = {
  MAX_TAX_PAYMENT_DAYS: process.env.MAX_TAX_PAYMENT_DAYS,
  MIN_VENDOR_DEPOSIT: process.env.MIN_VENDOR_DEPOSIT,
  MAX_VENDOR_DEPOSIT: process.env.MAX_VENDOR_DEPOSIT,
  MIN_VENDOR_WITHDRAWAL: process.env.MIN_VENDOR_WITHDRAWAL,
  MAX_VENDOR_WITHDRAWAL: process.env.MAX_VENDOR_WITHDRAWAL,
  MIN_SUPERVENDOR_DEPOSIT: process.env.MIN_SUPERVENDOR_DEPOSIT,
  MAX_SUPERVENDOR_DEPOSIT: process.env.MAX_SUPERVENDOR_DEPOSIT,
  MIN_SUPERVENDOR_WITHDRAWAL: process.env.MIN_SUPERVENDOR_WITHDRAWAL,
  MAX_SUPERVENDOR_WITHDRAWAL: process.env.MAX_SUPERVENDOR_WITHDRAWAL,
  MIN_WITHDRAWAL_AMOUNT: process.env.MIN_WITHDRAWAL_AMOUNT,
  BANK_TRANSFER_FEE: process.env.BANK_TRANSFER_FEE,
  MONNIFY_API_KEY: process.env.MONNIFY_API_KEY,
  MONNIFY_SECRET_KEY: process.env.MONNIFY_SECRET_KEY,
  MONNIFY_API_URL_V1: process.env.MONNIFY_API_URL_V1,
  MONNIFY_API_URL_V2: process.env.MONNIFY_API_URL_V2,
  MONNIFY_WALLET_ACCT_NUMBER: process.env.MONNIFY_WALLET_ACCT_NUMBER,
  MONNIFY_CONTRACT_CODE: process.env.MONNIFY_CONTRACT_CODE,
  MONNIFY_AUTH_HEADER: `Basic ${authString}`,
  MONNIFY_LIMIT_PROFILE_CODE_100K: process.env.MONNIFY_LIMIT_PROFILE_CODE_100K,
  MONNIFY_LIMIT_PROFILE_CODE_10K: process.env.MONNIFY_LIMIT_PROFILE_CODE_10K,
  MONNIFY_WEBHOOK_IP: process.env.MONNIFY_WEBHOOK_IP,
  INVOICE_EXPIRY_DAYS: process.env.INVOICE_EXPIRY_DAYS,
  GCP_PROJECT_ID: process.env.GCP_PROJECT_ID,
  GCS_BUCKET_NAME: process.env.GCS_BUCKET_NAME,
  GCS_BUCKET_URL: process.env.GCS_BUCKET_URL,
  DOMAIN_URL: process.env.DOMAIN_URL,
};

export const BUCKET_STORAGE_LOCATION ={
  VEHICLE_OWNERS_IMAGE: "vehicle-owner-images",
  DRIVERS_IMAGE: "driver-images",
};